### ISSUE TITLE
Incredibly high CPU usage (~1 fps) on 1.20.1

### ISSUE THREAD

**Issue by ColossalRenders** [wVibzz/ImmersiveWinds#32]
Using world generated with reTerraForged at world height 1024 causes fps drop to around one frame per second, specifically on mountains. When on flatter ground I get maybe 30 fps. Note that this is with all Distant Horizons features and shaders turned off (but still installed). When weather is not set to rain, I can run the game perfectly fine at 90 (capped) fps. 

![image](https://github.com/user-attachments/assets/30edaaf0-5688-46a7-a8c8-d0ccc065e4b6)
intel 13700f all cores maxed

Full mod list when the issue appeared. I have since removed everything except DH, Sodium, Iris, RTF, WWEE, Immersive Weathering, and dependencies, with no improvement:
![image](https://github.com/user-attachments/assets/aa05b7a4-ac62-4bac-9723-e745ce8a9bf8)

On vanilla worlds it's slightly better. If I turn off all DH rendering and distant generation it runs fine. (CPU usage at ~20%) If I turn on DH rendering and distant generation but set the weather to clear, it runs fine (CPU usage at ~90%, 70-90 (capped) fps). It's only with rain and distant generation that my frames drop to around 30.

**Comment by ColossalRenders** [comment]
Another issue I ran into with these mods: wind wisp consistently crashes game upon joining world. 

Reported exception thrown!
net.minecraft.class_148: Ticking Particle
at net.minecraft.class_702.method_3059(class_702.java:416)
at net.minecraft.class_702.method_3048(class_702.java:393)
at net.minecraft.class_702.method_18126(class_702.java:366)
at java.base/java.util.IdentityHashMap.forEach(IdentityHashMap.java:1354)
at net.minecraft.class_702.method_3057(class_702.java:364)
at net.minecraft.class_310.method_1574(class_310.java:1946)
at net.minecraft.class_310.method_1523(class_310.java:1181)
at net.minecraft.class_310.method_1514(class_310.java:802)
at net.minecraft.client.main.Main.main(Main.java:250)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_5649(double, double, double)" because "this.player" is null
at net.vibzz.immersivewind.particle.custom.WindWispParticle.method_3070(WindWispParticle.java:51)
at net.minecraft.class_702.method_3059(class_702.java:409)
... 11 more

**Comment by wVibzz** [comment]
Can you provide the log file instead of text? I can't do much from this.

**Comment by ColossalRenders** [comment]
For the crash or for the frame rate issue? I can do both but be warned for the latter DH spams my logs with multi line errors every tick or frame (it just does that if I have Iris installed); the log file is multiple GB and won't even open in notepad. 

I will be able to provide the log files later today hopefully.

**Comment by wVibzz** [comment]
> Another issue I ran into with these mods: wind wisp consistently crashes game upon joining world.
> 
> Reported exception thrown! net.minecraft.class_148: Ticking Particle at net.minecraft.class_702.method_3059(class_702.java:416) at net.minecraft.class_702.method_3048(class_702.java:393) at net.minecraft.class_702.method_18126(class_702.java:366) at java.base/java.util.IdentityHashMap.forEach(IdentityHashMap.java:1354) at net.minecraft.class_702.method_3057(class_702.java:364) at net.minecraft.class_310.method_1574(class_310.java:1946) at net.minecraft.class_310.method_1523(class_310.java:1181) at net.minecraft.class_310.method_1514(class_310.java:802) at net.minecraft.client.main.Main.main(Main.java:250) at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_5649(double, double, double)" because "this.player" is null at net.vibzz.immersivewind.particle.custom.WindWispParticle.method_3070(WindWispParticle.java:51) at net.minecraft.class_702.method_3059(class_702.java:409) ... 11 more

this one

**Comment by ColossalRenders** [comment]
https://mclo.gs/P1tBXAQ

In this instance I had all my mods loaded but the issue is still there when I'm only using the minimal setup I described in the original post (Cloth Config, Cristellib, DH, Wyther's EE, Fabric API, Fabric Kotlin, fzzy config, immersivewind 0.7, iris, particle core, particle rain, RTF, sodium)

**Comment by wVibzz** [comment]
i need to see the 11 more lines from that error

**Comment by wVibzz** [comment]
I think I solved it but I can only tell so much from what you gave me. The fix will be in the next update

**Comment by wVibzz** [comment]
Coming back to this issue its probably performance problems caused by Particle Rain lol. I know my fps tanked a little with it.
this wont be a problem in the next update though, ill have my own system for rain and snow.
